[package]
name = "honeybee"
version = "0.4.11"
authors = ["Douglas Lau <doug.lau@state.mn.us>"]
description = "Server for publishing IRIS data as JSON / MVT"
license = "GPL-2.0-or-later"
edition = "2018"

[dependencies]
base64 = "0.9"
log = "0.4"
env_logger = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
fallible-iterator = "0.1"
postgres = { version = "0.15" }
ssh2 = "0.3"
users = "0.7"
gif = "0.10"
