[workspace]
members = ["honeybee", "graft", "mayfly", "bulb"]
resolver = "2"

[workspace.package]
version = "5.45.0"
edition = "2021"

[profile.web]
inherits = "release"
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
