[package]
name = "bulb"
version = "0.0.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1"
serde = { version = "1", features = ["derive"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
wee_alloc = "0.4"

[dependencies.web-sys]
version = "0.3"
features = [
  'console',
  'CssStyleDeclaration',
  'Document',
  'HtmlCollection',
  'HtmlElement',
  'Window',
  'Event',
  'Headers',
  'HtmlInputElement',
  'HtmlLabelElement',
  'HtmlSelectElement',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
]

[profile.release]
opt-level = "s"
lto = true
# debug = true
