[package]
name = "graft"
version = "0.2.0"
description = "Web Server for proxying IRIS sonar objects"
license = "GPL-2.0-or-later"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-std = { version="1.8", features=["attributes"] }
convert_case = "0.4"
json = "0.12"
log = "0.4"
rustls = { version="0.19", features=["dangerous_configuration"] }
thiserror = "1.0"
tide = "0.16"
webpki = "0.21"

[dependencies.async-tls]
version = "0.11"
default-features = false
features = ["client"]

[dependencies.env_logger]
version = "0.8"
default-features = false
features = ["atty", "humantime"]
