[package]
name = "graft"
version = "0.1.0"
authors = ["Douglas Lau <doug.lau@state.mn.us>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-std = { version="1.8", features=["attributes"] }
convert_case = "0.4"
json = "0.12"
rustls = { version="0.19", features=["dangerous_configuration"] }
thiserror = "1.0"
tide = "0.16"
webpki = "0.21"

[dependencies.async-tls]
version = "0.11"
default-features = false
features = ["client"]
