[package]
name = "graft"
version = "0.2.0"
description = "Web Server for proxying IRIS sonar objects"
license = "GPL-2.0-or-later"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-std = { version="1.8", features=["attributes"] }
bb8 = "0.7"
bb8-postgres = "0.7"
chrono = "0.4"
convert_case = "0.5"
flume = "0.10"
log = "0.4"
percent-encoding = "2"
rand = "0.8"
rustls = { version="0.19", features=["dangerous_configuration"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tide = "0.16"
tokio = { version="1", features=["rt-multi-thread"] }
webpki = "0.21"
whoami = "1"

[dependencies.async-tls]
version = "0.11"
default-features = false
features = ["client"]

[dependencies.env_logger]
version = "0.9"
default-features = false
features = ["atty"]
