[package]
name = "mayfly"
version = "0.0.0"
authors = ["Douglas Lau <doug.lau@state.mn.us>"]
edition = "2018"

[dependencies]
async-std = { version="1.8", features=["attributes"] }
env_logger = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tide = "0.16"
zip = "0.5"
